/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as WorkerRouteRouteImport } from './routes/_worker/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as WorkerRouteImport } from './routes/worker'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AdminAdvancesRouteImport } from './routes/_admin/advances'
import { Route as AdminAssignmentsRouteImport } from './routes/_admin/assignments'
import { Route as AdminAttendanceRouteImport } from './routes/_admin/attendance'
import { Route as AdminDashboardRouteImport } from './routes/_admin/dashboard'
import { Route as AdminEmployeesRouteImport } from './routes/_admin/employees'
import { Route as AdminGodownsRouteImport } from './routes/_admin/godowns'
import { Route as AdminLeavesRouteImport } from './routes/_admin/leaves'
import { Route as AdminReportsRouteImport } from './routes/_admin/reports'
import { Route as AdminSalaryRouteImport } from './routes/_admin/salary'
import { Route as AdminSettingsRouteImport } from './routes/_admin/settings'
import { Route as AdminTemposRouteImport } from './routes/_admin/tempos'
import { Route as WorkerMyRouteImport } from './routes/_worker/my'
import { Route as ApiSyncRouteImport } from './routes/api/sync'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerRouteRoute = WorkerRouteRouteImport.update({
  id: '/_worker',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerRoute = WorkerRouteImport.update({
  id: '/worker',
  path: '/worker',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminAdvancesRoute = AdminAdvancesRouteImport.update({
  id: '/advances',
  path: '/advances',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAssignmentsRoute = AdminAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEmployeesRoute = AdminEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGodownsRoute = AdminGodownsRouteImport.update({
  id: '/godowns',
  path: '/godowns',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLeavesRoute = AdminLeavesRouteImport.update({
  id: '/leaves',
  path: '/leaves',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSalaryRoute = AdminSalaryRouteImport.update({
  id: '/salary',
  path: '/salary',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTemposRoute = AdminTemposRouteImport.update({
  id: '/tempos',
  path: '/tempos',
  getParentRoute: () => AdminRouteRoute,
} as any)
const WorkerMyRoute = WorkerMyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => WorkerRouteRoute,
} as any)
const ApiSyncRoute = ApiSyncRouteImport.update({
  id: '/api/sync',
  path: '/api/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/mcp': typeof McpRoute
  '/worker': typeof WorkerRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/advances': typeof AdminAdvancesRoute
  '/assignments': typeof AdminAssignmentsRoute
  '/attendance': typeof AdminAttendanceRoute
  '/dashboard': typeof AdminDashboardRoute
  '/employees': typeof AdminEmployeesRoute
  '/godowns': typeof AdminGodownsRoute
  '/leaves': typeof AdminLeavesRoute
  '/reports': typeof AdminReportsRoute
  '/salary': typeof AdminSalaryRoute
  '/settings': typeof AdminSettingsRoute
  '/tempos': typeof AdminTemposRoute
  '/my': typeof WorkerMyRoute
  '/api/sync': typeof ApiSyncRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/mcp': typeof McpRoute
  '/worker': typeof WorkerRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/advances': typeof AdminAdvancesRoute
  '/assignments': typeof AdminAssignmentsRoute
  '/attendance': typeof AdminAttendanceRoute
  '/dashboard': typeof AdminDashboardRoute
  '/employees': typeof AdminEmployeesRoute
  '/godowns': typeof AdminGodownsRoute
  '/leaves': typeof AdminLeavesRoute
  '/reports': typeof AdminReportsRoute
  '/salary': typeof AdminSalaryRoute
  '/settings': typeof AdminSettingsRoute
  '/tempos': typeof AdminTemposRoute
  '/my': typeof WorkerMyRoute
  '/api/sync': typeof ApiSyncRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteRouteWithChildren
  '/_worker': typeof WorkerRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/mcp': typeof McpRoute
  '/worker': typeof WorkerRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_admin/advances': typeof AdminAdvancesRoute
  '/_admin/assignments': typeof AdminAssignmentsRoute
  '/_admin/attendance': typeof AdminAttendanceRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/employees': typeof AdminEmployeesRoute
  '/_admin/godowns': typeof AdminGodownsRoute
  '/_admin/leaves': typeof AdminLeavesRoute
  '/_admin/reports': typeof AdminReportsRoute
  '/_admin/salary': typeof AdminSalaryRoute
  '/_admin/settings': typeof AdminSettingsRoute
  '/_admin/tempos': typeof AdminTemposRoute
  '/_worker/my': typeof WorkerMyRoute
  '/api/sync': typeof ApiSyncRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logout'
    | '/mcp'
    | '/worker'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/advances'
    | '/assignments'
    | '/attendance'
    | '/dashboard'
    | '/employees'
    | '/godowns'
    | '/leaves'
    | '/reports'
    | '/salary'
    | '/settings'
    | '/tempos'
    | '/my'
    | '/api/sync'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logout'
    | '/mcp'
    | '/worker'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/advances'
    | '/assignments'
    | '/attendance'
    | '/dashboard'
    | '/employees'
    | '/godowns'
    | '/leaves'
    | '/reports'
    | '/salary'
    | '/settings'
    | '/tempos'
    | '/my'
    | '/api/sync'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_worker'
    | '/login'
    | '/logout'
    | '/mcp'
    | '/worker'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_admin/advances'
    | '/_admin/assignments'
    | '/_admin/attendance'
    | '/_admin/dashboard'
    | '/_admin/employees'
    | '/_admin/godowns'
    | '/_admin/leaves'
    | '/_admin/reports'
    | '/_admin/salary'
    | '/_admin/settings'
    | '/_admin/tempos'
    | '/_worker/my'
    | '/api/sync'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  WorkerRouteRoute: typeof WorkerRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  McpRoute: typeof McpRoute
  WorkerRoute: typeof WorkerRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiSyncRoute: typeof ApiSyncRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_worker': {
      id: '/_worker'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker': {
      id: '/worker'
      path: '/worker'
      fullPath: '/worker'
      preLoaderRoute: typeof WorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/advances': {
      id: '/_admin/advances'
      path: '/advances'
      fullPath: '/advances'
      preLoaderRoute: typeof AdminAdvancesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/assignments': {
      id: '/_admin/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AdminAssignmentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/attendance': {
      id: '/_admin/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/employees': {
      id: '/_admin/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AdminEmployeesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/godowns': {
      id: '/_admin/godowns'
      path: '/godowns'
      fullPath: '/godowns'
      preLoaderRoute: typeof AdminGodownsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/leaves': {
      id: '/_admin/leaves'
      path: '/leaves'
      fullPath: '/leaves'
      preLoaderRoute: typeof AdminLeavesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/reports': {
      id: '/_admin/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/salary': {
      id: '/_admin/salary'
      path: '/salary'
      fullPath: '/salary'
      preLoaderRoute: typeof AdminSalaryRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/settings': {
      id: '/_admin/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/tempos': {
      id: '/_admin/tempos'
      path: '/tempos'
      fullPath: '/tempos'
      preLoaderRoute: typeof AdminTemposRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_worker/my': {
      id: '/_worker/my'
      path: '/my'
      fullPath: '/my'
      preLoaderRoute: typeof WorkerMyRouteImport
      parentRoute: typeof WorkerRouteRoute
    }
    '/api/sync': {
      id: '/api/sync'
      path: '/api/sync'
      fullPath: '/api/sync'
      preLoaderRoute: typeof ApiSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAdvancesRoute: typeof AdminAdvancesRoute
  AdminAssignmentsRoute: typeof AdminAssignmentsRoute
  AdminAttendanceRoute: typeof AdminAttendanceRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEmployeesRoute: typeof AdminEmployeesRoute
  AdminGodownsRoute: typeof AdminGodownsRoute
  AdminLeavesRoute: typeof AdminLeavesRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSalaryRoute: typeof AdminSalaryRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTemposRoute: typeof AdminTemposRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAdvancesRoute: AdminAdvancesRoute,
  AdminAssignmentsRoute: AdminAssignmentsRoute,
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEmployeesRoute: AdminEmployeesRoute,
  AdminGodownsRoute: AdminGodownsRoute,
  AdminLeavesRoute: AdminLeavesRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSalaryRoute: AdminSalaryRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTemposRoute: AdminTemposRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface WorkerRouteRouteChildren {
  WorkerMyRoute: typeof WorkerMyRoute
}

const WorkerRouteRouteChildren: WorkerRouteRouteChildren = {
  WorkerMyRoute: WorkerMyRoute,
}

const WorkerRouteRouteWithChildren = WorkerRouteRoute._addFileChildren(
  WorkerRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  WorkerRouteRoute: WorkerRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  McpRoute: McpRoute,
  WorkerRoute: WorkerRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiSyncRoute: ApiSyncRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
